### ISSUE TITLE
Enabling cluster support

### ISSUE THREAD

**Issue by mortonjt** [gibsramen/BIRDMAn#11]
MCMC will take ages to run if computation is performed on a single compute node (negative binomial will take ~24 hours on 1000 microbes, 1000 samples on 1 core).

So getting large-scale cluster support is going to a huge enabler here.  See https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html

**Comment by gibsramen** [comment]
Marking this as closed via #30. If specific problems arise or new functionality is requested feel free to open a new issue.
