### ISSUE TITLE
Temporary files usage

### ISSUE THREAD

**Issue by mortonjt** [gibsramen/BIRDMAn#36]
One thing that I've been noticing is that right after a CmdStanMCMC session exits, all of the temporarily files are deleted.
So if one wishes to perform diagnostics or create InferenceData objects in a cluster setting, they won't be able to.

There are two approaches to fixing this problem
1. Figure out how to not use temporary files with Stan by specifying the `output_directory`
2. Create InferenceData objects directly the CmdStanMCMC objects in the same session, and pass around InferenceData objects instead.

I've gotten the 2nd strategy working on `q2-differential`.  The problem here is that it will be more difficult to perform cross-validation down the road (which is still pending due to https://github.com/stan-dev/cmdstanpy/issues/345, https://github.com/stan-dev/cmdstanpy/issues/251)

**Comment by gibsramen** [comment]
For (1) can we pass `output_dir` into the `sampler_args` dict of `Model.fit`?

**Comment by mortonjt** [comment]
Closing this, since this is no longer relevant with the new architecture
